api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 4 # Adjust the default number of items per page
    
    
    
    
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
